export default {
  "index": "Overview",
  "sep-start": { type: "separator", title: "Getting Started" },
  "getting-started": "Getting Started",
  "sep-review": { type: "separator", title: "Code Review" },
  "how-it-works": "Review Engine",
  "evidence-and-provenance": "Evidence & Provenance",
  "integrations": "GitHub App",
  "triage": "Triage",
  "sep-cli": { type: "separator", title: "CLI" },
  "cli-and-chat": "CLI & Chat",
  "mcp": "MCP",
  "slack-assistant": "Slack",
  "sep-config": { type: "separator", title: "Models & Configuration" },
  "configuration": "Configuration",
  "usage-limits": "Usage & Limits",
  "sep-reference": { type: "separator", title: "Reference" },
  "api-reference": "API",
  "operations-and-releases": "Operations",
  "troubleshooting": "Troubleshooting",
}
