export default {
  "index": "Introduction",
  "sep-start": { type: "separator", title: "Getting Started" },
  "getting-started": "Getting Started",
  "sep-review": { type: "separator", title: "Code Review" },
  "how-it-works": "How It Works",
  "triage": "Triage",
  "evidence-and-provenance": "Evidence & Provenance",
  "integrations": "Integrations",
  "sep-cli": { type: "separator", title: "CLI & Chat" },
  "cli-and-chat": "CLI & Deep Research",
  "mcp": "MCP",
  "sep-models": { type: "separator", title: "Models" },
  "models": "Models",
  "sep-usage": { type: "separator", title: "Usage & Limits" },
  "usage-and-limits": "Usage & Limits",
  "sep-config": { type: "separator", title: "Configuration" },
  "configuration": "Configuration",
  "operations-and-releases": "Operations & Releases",
  "troubleshooting": "Troubleshooting",
  "sep-slack": { type: "separator", title: "Slack Assistant" },
  "slack-assistant": "Slack Assistant",
  "sep-api": { type: "separator", title: "API Reference" },
  "api-reference": "API",
}
