export default {
  "index": "Introduction",
  "sep-platform": { type: "separator", title: "Platform" },
  "getting-started": "Getting Started",
  "how-it-works": "How It Works",
  "sep-memory": { type: "separator", title: "Memory — the moat" },
  "memory": "Memory",
  "sep-platform-2": { type: "separator", title: "Platform" },
  "triage": "Triage",
  "evidence-and-provenance": "Evidence & Provenance",
  "integrations": "Integrations",
  "sep-cli": { type: "separator", title: "CLI & Deep Research" },
  "cli-and-chat": "CLI & Deep Research",
  "sep-slack": { type: "separator", title: "Slack Assistant" },
  "slack-assistant": "Slack Assistant",
  "sep-config": { type: "separator", title: "Configuration" },
  "configuration": "Configuration",
  "operations-and-releases": "Operations & Releases",
  "troubleshooting": "Troubleshooting",
}
