export default {
  "the-ensemble": "The Ensemble",
  "the-dispatcher": "The Dispatcher",
  "specialists": "Specialists",
  "synthesizer": "Synthesizer (Harmonia)",
  "believability-pipeline": "The Believability Pipeline",
  "deterministic-checks": "Deterministic Checks",
  "confidence-scoring": "Confidence & Proof Tiers",
  "verification": "Verification & Trust Ledger",
  "review-lifecycle": "Review Lifecycle",
  "review-memory": "Review Memory",
  "conversational-learnings": "Conversational Learnings",
  "code-graph": "Code Graph & Blast Radius",
  "earned-context": "Earned Context",
}
